### ISSUE TITLE
集成遇到jdk版本问题

### ISSUE THREAD

**Issue by sky4star** [lambdacloud/LambdacloudSDK#3]
[dx] indicate that it is *not* an inner class.
[dex] Pre-Dexing /Users/xiaomao/svn_workspace/client/trunk/low/SevengaSDK/libs/bolts.jar -> bolts-e5e0f6b8d2c45c46a2e3c6c8e904926c.jar
[dex] Pre-Dexing /Users/xiaomao/svn_workspace/client/trunk/low/Low/proj.android/libs/logsdk-0.0.1.jar -> logsdk-0.0.1-ef550bb19ba2a0ed499a50aa5db992af.jar
[dx] 
[dx] UNEXPECTED TOP-LEVEL EXCEPTION:
[dx] com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
[dx] 	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
[dx] 	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
[dx] 	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
[dx] 	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
[dx] 	at com.android.dx.command.dexer.Main.processClass(Main.java:665)
[dx] 	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:634)
[dx] 	at com.android.dx.command.dexer.Main.access$600(Main.java:78)
[dx] 	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:572)
[dx] 	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
[dx] 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
[dx] 	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
[dx] 	at com.android.dx.command.dexer.Main.processOne(Main.java:596)
[dx] 	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:498)
[dx] 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:264)
[dx] 	at com.android.dx.command.dexer.Main.run(Main.java:230)
[dx] 	at com.android.dx.command.dexer.Main.main(Main.java:199)
[dx] 	at com.android.dx.command.Main.main(Main.java:103)
[dx] ...while parsing com/lambdacloud/sdk/android/DeviceInfo.class
[dx] 
[dx] 1 error; aborting

**Comment by sky4star** [comment]
貌似是因为我之前提供的是用jdk1.8编译的，安装jdk 1.7，然后重新mvn编译就正常了

**Comment by sky4star** [comment]
- [ ] brew cask install java7 安装jdk7
 - [ ] mvn clean compile package 重新编译，其中设置maven-android-plugin.configuration.sdk.platform 为17
 - [ ] javap -v target/classes/com/lambdacloud/sdk/android/DeviceInfo.class | grep "version" 查看编译的版本 

 - [ ] 另外在Intellij中也可以编译出jar，注意选择Maven Android API 17 Platform jave version为1.7

**Comment by sky4star** [comment]
set java home
  * http://www.mkyong.com/java/how-to-set-java_home-environment-variable-on-mac-os-x/
  * edit  ~/.bash_profile
  * /usr/libexec/java_home -v 1.7 来切换jdk

**Comment by wezhang** [comment]
wiki中有相应章节：https://github.com/lambdacloud/lanyun/wiki/DEV-%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83-MacOS#%E7%AE%A1%E7%90%86%E5%A4%9A%E7%89%88%E6%9C%AC%E7%9A%84java
